### ISSUE TITLE
Add UUID to each `atom-cli` element instance.

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#106]
Now that it's installed in the nucleus, we want to be able to launch multiple instances of it in the same container and encourage developers to use the copy in the nucleus since it will always be up-to-date. For now we're just using the container ID for the element, we should add some other UUID, perhaps a random string or something.

**Comment by dpipemazo** [comment]
This is still an issue and should be a decently high priority

**Comment by cheripai** [comment]
Fixed
We now append a UUID4 hex string to the element name
