### ISSUE TITLE
Docs in atombot tutorial for `msgpack false` missing second line

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#159]
When looking at the "copy" button for the `msgpack false` section of the atombot docs we are missing the line showing:
```
> msgpack false
```

**Comment by dpipemazo** [comment]
![msgpack-false-docs](https://user-images.githubusercontent.com/2764032/58981919-3837e500-8788-11e9-812c-3e2902cb1d73.png)

**Comment by cheripai** [comment]
fixed
