### ISSUE TITLE
Better documentation of xhost permissions

### ISSUE THREAD

**Issue by plipay** [elementary-robotics/atom#182]
`xhost +SI:localuser:root` is sometimes required before you can run GUI atom apps, should be better documented

**Comment by Cody-G** [comment]
I can make this clearer in the docs, but currently executing that command isn't enough for me to get everything running locally.  I haven't yet found a way to get all of the GUI apps from the [tutorial](http://robotics.atomdocs.io/#getting-started-with-atom-os) to work locally, despite using that command and trying several modifications to the docker-compose file.  I did find one configuration that worked for everything except the simulator app.  Can anyone else run everything locally at the moment?

**Comment by Cody-G** [comment]
This was mentioned a few times in the walkthrough, but it wasn't so easy to find.  I've added it to a new SDK-Graphics section of the docs in #224
