### ISSUE TITLE
RFC: Image references

### ISSUE THREAD

**Issue by Cody-G** [elementary-robotics/atom#228]
Currently every time we send/receive an image to/from an element we go through a process like the one below:

```python
import atom
import numpy as np
import cv2

element = atom.Element("demo")
img = np.zeros((100,100), dtype=np.uint8)


#encode numpy array as image
_, img_serialized = cv2.imencode(".tif", img)

#encoded image to bytes
img_bytes = img_serialized.tobytes()

#create atom reference
img_ref = element.reference_create(img_bytes)[0]

#get atom reference
img_got_dict = element.reference_get(img_ref)
img_got_bytes = img_got_dict[img_ref]

#decode from buffer
#img_got should be the same as img above
img_got = cv2.imdecode(np.frombuffer(img_got_bytes, dtype=np.uint8), flags=cv2.IMREAD_UNCHANGED)
```

I see three disadvantages to this approach:

1. We duplicate a lot of code.  The steps above are enacted at least once in each element that handles images.  It's a lot to type and remember, and not so intuitive for new developers.
2. The steps above make an assumption about the encoding of pixel values (in this case `uint8`).  This means that both the sending and receiving element must know and agree on the types.  That will become a problem when running image processing algorithms on images from cameras with greater than 8-bit precision _or_ in intermediate processing steps that typically encode as `float`.  We're also restricted to 2D images (fine because we don't deal with 3D currently but we may at some point).
3. The above approach isn't very efficient, as each call to `cv2.imdecode` and `cv2.imencode` create copies.  I count 5 copies of the image in memory after executing the code snippet above (including Redis memory).

I think # 1 is the simplest to solve.  I think the minimal way to do it is to add functionality to `atom` for creating and getting image references, something like `element.reference_image_create` and `element.reference_image_get`.  # 2 is more difficult and there are a number of solutions that we could discuss.  One could always pass the pixel types to / from elements, along with references, but I think this gets tedious.  Ultimately we may want to integrate image / array support into atom.  # 3 is the least concerning for me because I don't think it's a performance bottleneck at the moment, but it's something to keep in mind.  All three issues could be addressed by using something like [FlatBuffers](https://google.github.io/flatbuffers/) to handle images, but I recognize that could be a lot of work; we could instead implement something more custom and lightweight specifically for array data.

**Comment by dpipemazo** [comment]
@Cody-G I see the points being raised, and I think we should consider the following questions and the original intent of Atom.

Atom is intended to be a language-agnostic message-passing protocol at its core. With our current dependencies on `redis` and `msgpack` we support around 50 languages. Any decision that we make that restricts the language support needs to be considered very carefully.

(1) -- I'm not sure I see the issue. This is more of a Python problem than an Atom problem. Assuming your data comes in as TIF it's really just one step to convert from TIF to bytes and then send the bytes through Atom. For most of our references being created the data is being read from an Atom stream anyway in which case it's already TIF serialized most of the time. 
(2) -- One of the core principles of Atom is that we expect the publisher and reader of data to agree on the serialization protocol. We're not making any assumptions -- where the publisher specifies the data is `uint8` we decode as `uint8`, where it's something like a point cloud we decode accordingly. The entity reading/decoding data is expected to have consulted the docs for the publisher before doing so which I do not think is an unreasonable burden. We made the docs website to publish the READMEs to make this as easy as possible. This is what allows us to not enforce a serialization format on the wire.
(3) -- This also seems like Python/OpenCV problem and not a dependency I think we need to work into Atom. Even if we were to move the code into the atom library it would still be happening I think?
