### ISSUE TITLE
RFC: Integrate Apache Arrow as a serialization option

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#230]
@Cody-G has pointed out a few use cases where our current serialization options aren't optimal -- specifically large, structured arrays/matrices that aren't necessarily images. In these instances `msgpack` is [not great](http://satoru.rocks/2018/08/fastest-way-to-serialize-array/) and [Apache Arrow](https://arrow.apache.org/) is much better. Arrow's language support, though not at the same level as Redis's or MsgPack's is quite solid and would likely cover the majority of use cases in which one would be processing such arrays.

Interested to hear thoughts on:
1. Adding Arrow as a serialization option
2. If (1), then should we change the serialization args from T/F to one of a list of options, such as in Python, changing from:
```
entry_write(..., serialize=True)
```
to
```
entry_write(..., serialization="msgpack")
```
or similar

**Comment by Cody-G** [comment]
I only just found out about Apache Arrow, but this sounds great!  It should be faster than msgpack by a few orders of magnitude, and in many cases numpy arrays can be decoded from arrow arrays without copying memory.

As for the implementation, I prefer to make `serialization` a string keyword argument as @dpipemazo suggested.  If people are concerned about disruption then a less breaking change would be to keep `serialize` as a T/F switch, and then add _another_ keyword argument `serialization` that sets the default serialization backend to msgpack, and that argument would be ignored if `serialize` is False.

**Comment by dpipemazo** [comment]
I like the idea of keeping `serialize=True` for legacy purposes and then adding the new option :+1:

**Comment by aywaldron** [comment]
@dpipemazo Does this issue pertain to just the `entry_write` method or other methods that have the `serialize` option as well?

**Comment by dpipemazo** [comment]
@aywaldron this would apply to all APIs. It would allow the user to select a different option from `msgpack` when choosing to serialize leaving their choices as:
1. No serialization (raw data being sent/received)
2. Serialization with msgpack
3. Serialization with arrow

It would also need to be added into `atom-cli` so that we can send/receive/read arrow-serialized data
