### ISSUE TITLE
Build improvement ideas

### ISSUE THREAD

**Issue by aywaldron** [elementary-robotics/atom#244]
- Use [contexts](https://circleci.com/docs/2.0/contexts/) in CircleCI for storing org-wide env vars so they don't have to be set on every job
- Use [circleci/orb-tools orb](https://circleci.com/orbs/registry/orb/circleci/orb-tools) for automated publishing of atom orb
- Remove test dependencies like valgrind from atom image and install them in running container during the build
- Look into https://circleci.com/orbs/registry/orb/cci-x/docker-registry-image-cache

**Comment by dpipemazo** [comment]
I think as of #299 being merged removing test dependencies and image caching are covered.
