### ISSUE TITLE
Tagged builds using our orb bump `latest`

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#275]
`latest` should only be bumped from `master` builds -- tags should not also bump `latest` and I believe they currently are

**Comment by aywaldron** [comment]
@dpipemazo This is actually a change that would need to be made to individual build config.ymls, not the orb. I pushed this change to atom and to the orb example config.

**Comment by dpipemazo** [comment]
Ah, I see. In talking to the CircleCI team they'll be adding workflows to orbs in the future that would help us a bit with this.
