### ISSUE TITLE
Add command to orb to run standard `flake8` check against the code

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#276]
We've generally agreed on internal Python coding style with the following `flake8` config settings:

```
[flake8]
max-line-length = 120
max-doc-length = 80
select = C,E,F,W,B
ignore = E203,W503
```

We should have a command in our orb that allows us to check for these. We don't need to apply it on all repos (and I'm not sure `atom/python` would pass for now), but it would help with other repos throughout the company.

**Comment by aywaldron** [comment]
Example: https://github.com/elementary-robotics/spec-robot/blob/920be40f8336674124139abdb6975ebf2a6c18c1/.circleci/config.yml#L23
