### ISSUE TITLE
Download test dependencies with git-lfs

### ISSUE THREAD

**Issue by Cody-G** [elementary-robotics/atom#321]
Some of our ML/CV repose have been downloading image data for CI testing by pulling the images with git-lfs in the test stage of CI.  This allows us to keep the test dependency data out of the final built images.  With the new build flow I don't see a way to do this.  I did see that we have a `use_git_lfs` flag on our build command (see [here](https://github.com/elementary-robotics/atom/blob/master/.circleci/atom.yml#L493-L496)), but I see nothing similar for our test command.  Is there a way to do this with the new build scheme?  In the past we did this with a list of explicit commands, as shown for example [here](https://github.com/elementary-robotics/element-barcode/blob/master/.circleci/config.yml#L19-L39), but I'm not sure how to replicate that now.

This is currently causing the test failure at https://github.com/elementary-robotics/element-barcode/pull/21

**Comment by dpipemazo** [comment]
Solved in #323
