### ISSUE TITLE
Add environment variables to control redis connection

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#351]
We want to agree on and implement in the Atom clients a set of environment variables which dictate which redis we connect to as our "nucleus" for a given element as well as which method we use (TCP vs socket). These environment variables would only be used in the event that explicit arguments aren't passed to the element constructor as these are already arguments to the constructor.

If we implement this in the element spec we can then easily point our docker containers at different hosts through standardized docker-compose variables which would be quite nice. 

@Cody-G

**Comment by Cody-G** [comment]
Sounds great!  As we discussed, one immediate benefit of this is that we can point `stream-viewer` at an image stream on a remote host, though there are plenty of other use cases.
