### ISSUE TITLE
wait_for_nucleus script needed for CI testing

### ISSUE THREAD

**Issue by Cody-G** [elementary-robotics/atom#363]
I just realized that we can experience the same race condition that motivated us to use the `wait_for_nucleus.sh` script when launching and running our test containers in circleci.  I addressed this in the new defect-detection tests by editing the circle config: https://github.com/elementary-robotics/element-defect-detection/pull/106/commits/2328d8ad0f3d823230e320bf07711f2825cd8a56

I suspect we're going to have similar testing issues across other repos.  Either we could edit the config on all of them as above or perhaps fix this generally in the CircleCi commands.  The Atom repo probably isn't the best place to file this issue, but since we don't have a circleci repo I'm putting this here.

**Comment by dpipemazo** [comment]
We can add it to the CircleCI orb, but we can also just invoke it when invoking the test commands as a workaround for now.
