### ISSUE TITLE
Add type annotations to `languages/python/atom/element.py`

### ISSUE THREAD

**Issue by kylebebak** [elementary-robotics/atom#407]
This is actually where the type hint value:effort ratio is highest, because pretty much everything running on the "camera side" depends on Atom.

We don't need all the code in this repo to be annotated, just the method/function signatures, so that anything that depends on Atom can use those type hints (e.g. vision-processing, to which we're adding type hints now, https://github.com/elementary-robotics/vision-processing/issues/126).

Adding type hints to method/function signatures would require minimal effort.

**Comment by slaigai** [comment]
I've added type hints to most of atom to help with the [related ticket](elementary-robotics/vision-processing#126). I'll open a PR for this ticket with changes, but the scope would be expanded to all python files in `languages/python/atom`

**Comment by slaigai** [comment]
Expanding scope to add type checker to CI pipeline temporarily with the plan to transition after #413 is sorted out.
