### ISSUE TITLE
Update `isort` to 5.8.0 and add `--overwrite-in-place` flag

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#415]
Once released, this will improve the formatter experience to no longer reclaim files under `root` ownership and instead edit in-place. Functionality is not fully out yet, see https://github.com/PyCQA/isort/issues/1644#issuecomment-791160120.

Thank you `isort` team!

**Comment by slaigai** [comment]
5.8.0 has been released! https://github.com/PyCQA/isort/releases/tag/5.8.0
