### ISSUE TITLE
Add `serdes` or similar key to all streams

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#77]
We should note in the stream the type of serialization being used. This would make it a bit more obvious and allow the CLI to better interpret the forms of data

**Comment by Cody-G** [comment]
On the Python side I want to be sure what you mean here.  As far as I can tell we don't have anything like a `Stream` class in Python, instead we just use the names of Redis streams and track whether to serialize or not through separate flag arguments.  Would you like me to implement something like a `Stream` class that has keys for the Redis stream name and the serialization setting, thus reducing the need for the flag arguments?

**Comment by dpipemazo** [comment]
@aywaldron has now implemented this in #234 :slightly_smiling_face:
